# Generated by Django 4.2.15 on 2024-08-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flux',
            name='budget_or_real',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.budgetreal'),
        ),
        migrations.AddField(
            model_name='flux',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
        migrations.AddField(
            model_name='flux',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.period'),
        ),
        migrations.AddField(
            model_name='flux',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.subcategory'),
        ),
    ]
