# Generated by Django 4.2.15 on 2024-08-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_period_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='flux',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flux',
            name='annual_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flux',
            name='year',
            field=models.IntegerField(default=1966),
        ),
    ]
