# Generated by Django 4.2.15 on 2024-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_flux_amount_flux_annual_amount_flux_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='flux',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flux',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
